const data_notification = 
[
    {
        _id: '1',
        avater: '/images/AvaterImage-001.jpg',
        icon_feel: '/images/cookie.svg',
        name_user: 'Em bé nhỏ',
        status_action:  "chấp nhận lời mời kết bạn", 
        icon_action: '/images/happy.svg',         
        comment_action: "Tao coi mày vui vẻ được bao lâu",
        time_action: "10 phút trước",
        follow_member: "Follow",
    },
    {
        _id: '2',
        avater: '/images/AvaterImage-002.jpg',
        icon_feel: '/images/cry.svg',
        name_user: 'Tình yêu bé nhỏ',
        status_action: "đã bày tỏ cảm xúc",
        icon_action: '/images/happy.svg',      
        comment_action: "Thôi chia tay",
        time_action: "3 giờ trước",
        follow_member: "Follow",
    },
    {
        _id: '3',
        avater: '/images/AvaterImage-003.jpg',
        icon_feel: '/images/happy.svg',
        name_user: 'Cô bé mới lớn',
        status_action: "đã nhắc đến bạn",         
        icon_action: '/images/happy.svg',     
        comment_action: "Chào bạn",
        time_action: "1 ngày trước",
        follow_member: "Unfollow",
    },
    {
        _id: '4',
        avater: '/images/AvaterImage-004.jpg',
        icon_feel: '/images/friendly.svg',
        name_user: 'Trẻ con tiến hóa',
        status_action: "bạn đã đăng nhập vào",
        icon_action: '/images/happy.svg', 
        comment_action: "Bạn ơi hôm nay bạn đẹp lắm",
        time_action: "4 ngày trước",
        follow_member: "Unfollow",
    },
    {
        _id: '5',
        avater: '/images/AvaterImage-005.jpg',
        icon_feel: '/images/cookie.svg',
        name_user: 'Tập chơi Dak',
        status_action:  "chấp nhận lời mời kết bạn", 
        icon_action: '/images/happy.svg',         
        comment_action: "Tao coi mày vui vẻ được bao lâu",
        time_action: "10 phút trước",
        follow_member: "Follow",
    },
    {
        _id: '6',
        avater: '/images/AvaterImage-001.jpg',
        icon_feel: '/images/cry.svg',
        name_user: 'Tình yêu bé nhỏ',
        status_action: "đã bày tỏ cảm xúc",
        icon_action: '/images/happy.svg',      
        comment_action: "Thôi chia tay",
        time_action: "3 giờ trước",
        follow_member: "Follow",
    },
    {
        _id: '7',
        avater: '/images/AvaterImage-002.jpg',
        icon_feel: '/images/happy.svg',
        name_user: 'Sát thủ tình trường',
        status_action: "đã nhắc đến bạn",         
        icon_action: '/images/happy.svg',     
        comment_action: "Tàu nhanh 500k",
        time_action: "1 ngày trước",
        follow_member: "Unfollow",
    },
    {
        _id: '8',
        avater: '/images/AvaterImage-003.jpg',
        icon_feel: '/images/friendly.svg',
        name_user: 'Cô gái gợi cảm',
        status_action: "bạn đã đăng nhập vào",
        icon_action: '/images/happy.svg', 
        comment_action: "Anh ơi có tour 3 ngày 2 đêm không",
        time_action: "4 ngày trước",
        follow_member: "Unfollow",
    }
]

export default data_notification;