import Head from 'next/head'
import React from 'react'
import Layout, { siteTitle } from '../components/Layout/Layout'
import Styled from '../styles/Home.module.css'
import Newsfeed from '../components/newsfeed/Newsfeed';
import Shortcut from '../components/Shortcut/Shortcut';
import PopupStatistic from '../components/UserProfile/PopupStatistic/PopupStatistic'
import Header from '../components/Header/Header'
import BoxChat from '../components/BoxChat/BoxChat'
import { BoxChatProvider } from '../components/BoxChat/BoxChatContext'

export default function Home() {
  return (
    <>  
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <title>{siteTitle}</title>  
    </Head>
    {/* <BoxChatProvider> */}
      {/* Layout */}
      <Layout>
        {/* Nav head */}
        <Header /> 
        {/* Lối tắt */}
        <Shortcut />
        
        {/* Bản tin (home page) */}   
        <Newsfeed />
        
        <BoxChat isShowItemChatBox/>
      </Layout>
      <PopupStatistic />
    {/* </BoxChatProvider> */}
    </>
  )
}
